config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "rooms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/board.rb
module Board
  extend ActiveSupport::Concern

  # 0 | 1 | 2
  # 3 | 4 | 5
  # 6 | 7 | 8
  WIN_COMBINATIONS = [
    [0, 1, 2], [3, 4, 5], [6, 7, 8], # horizontal
    [0, 3, 6], [1, 4, 7], [2, 5, 8], # vertical
    [0, 4, 8], [2, 4, 6],
  ]

  def equals3(a, b, c)
    a != "" && a == b && b == c
  end

  def won?
    WIN_COMBINATIONS.each do |combination|
      if equals3 board[combination[0]], board[combination[1]], board[combination[2]]
        return board[combination[0]]
      end
    end

    unless board.include? ""
      return "Tie"
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  extend FriendlyId
  include Board

  serialize :players, Array
  serialize :board, Array

  friendly_id :name, use: [:slugged, :finders]

  validates :name, uniqueness: true, presence: true

  before_create :assign_board

  def assign_board
    self.board = [""] * 9
  end

  def update_board(params)
    self.board[params["index"].to_i] = params["current"]
    self.current = params["current"] == "X" ? "O" : "X"

    save
  end

  def player_exist?(uuid)
    players.length > 1 || players.include?(uuid)
  end

  def is_played?(uuid)
    puts players
    (current == "O" && players.first == uuid) || (current == "X" && players.second == uuid)
  end

  def clear
    assign_board
    self.current = "X"
    save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_cookie

  private

  def set_cookie
    cookies[:uuid] ||= SecureRandom.uuid
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
      @room = Room.new
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    unless @room.player_exist? cookies[:uuid]
      @room.players << cookies[:uuid]
      @room.save
    end

    @disabled = @room.is_played?(cookies[:uuid]) ? "disabled" : ""
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)
    puts @room, room_params
    if @room.save
      redirect_to @room, notice: "Room was successfully created."
    else
      render :index, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    @room.update_board(update_params)
    ActionCable.server.broadcast "room_channel_#{@room.slug}",
      { room: @room, playerId: cookies[:uuid], won: @room.won? }

    @room.clear if @room.won?

    respond_to do |format|
      format.json { render :update }
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def room_params
    params.require(:room).permit(:name, :slug)
  end

  def update_params
    params.require(:room).permit(:index, :current)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tictactoe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <%= yield %>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div class="errors">
      <div class="header"><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</div>

      <ul class="error-list">
        <% room.errors.each do |error| %>
          <li class="error-list-item">Room <%= error.message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form.label :room %>
  <%= form.text_field :name %>  

  <%= form.submit %>
<% end %>

app/views/rooms/_game_board.html.erb
<% 3.times do |row| %>
  <div>
    <% 3.times do |col| %>
      <% index=row + col * 3 %>
      <div class="cell" data-action="click->room#play" data-index="<%= index %>" data-url="<%= room_path %>">
        <%= room.board[index] %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/rooms/index.html.erb
<div class="center">
  <div class="container">
    <div><%= render "title" %></div>
    
    <div>
      <%= render "form", room: @room %>
    </div>
    
    <div class="instructions">
      <div class="q">How to play</div>
      <ul>
        <li>Create a room</li>
        <li>Share room url with other player</li>
        <li>Play & Enjoy 👾</li>
      </ul>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="center">
  <div>
    <%= render "title" %>
  </div>

  <% if @room.players.include? cookies[:uuid] %>
    <div>Playing as <%= @room.players[0] == cookies[:uuid] ? 'X' : 'O' %></div>
    <div id="room_id" data-channel="<%= @room.friendly_id %>" data-controller="room"
      data-current="<%= @room.current %>" class="container <%= @disabled %> justify-content-center">
      <%= render "game_board", room: @room %>
    </div>
    <div class="share-url">
      share below url to play with your friend
      <br><span class="url"><%= room_url(@room) %></span><br>
    </div>
  <% else %>
    <div>This board is full</div>
  <% end %>

  <%= link_to 'Reset', room_path(@room.friendly_id), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: 'btn btn-primary' %>
</div>